"""viaticos_mejoras

Revision ID: 403ee767f5cd
Revises: 537ee15fde09
Create Date: 2026-03-30 09:18:48.307406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '403ee767f5cd'
down_revision: Union[str, Sequence[str], None] = '537ee15fde09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viaticos', sa.Column('tipo_transporte', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('viaticos', sa.Column('cotizacion_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_viaticos_cotizacion_id'), 'viaticos', ['cotizacion_id'], unique=False)
    op.create_foreign_key(None, 'viaticos', 'cotizaciones', ['cotizacion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'viaticos', type_='foreignkey')
    op.drop_index(op.f('ix_viaticos_cotizacion_id'), table_name='viaticos')
    op.drop_column('viaticos', 'cotizacion_id')
    op.drop_column('viaticos', 'tipo_transporte')
    # ### end Alembic commands ###
