"""add_viatico_id_to_concepto_cotizacion

Revision ID: ef321a123f4a
Revises: 403ee767f5cd
Create Date: 2026-04-05 08:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ef321a123f4a'
down_revision: Union[str, Sequence[str], None] = '403ee767f5cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic ###
    op.add_column('conceptocotizacion', sa.Column('viatico_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_conceptocotizacion_viatico_id'), 'conceptocotizacion', ['viatico_id'], unique=False)
    op.create_foreign_key(None, 'conceptocotizacion', 'viaticos', ['viatico_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic ###
    op.drop_constraint(None, 'conceptocotizacion', type_='foreignkey')
    op.drop_index(op.f('ix_conceptocotizacion_viatico_id'), table_name='conceptocotizacion')
    op.drop_column('conceptocotizacion', 'viatico_id')
    # ### end Alembic commands ###
