"""viaticos_refactor

Revision ID: 537ee15fde09
Revises: f6334f4e04b3
Create Date: 2026-03-27 20:29:10.512200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '537ee15fde09'
down_revision: Union[str, Sequence[str], None] = 'f6334f4e04b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viaticos',
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text("date_trunc('second', now())"), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_por', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modificado_por', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subtotal', sa.Numeric(scale=2), nullable=False),
    sa.Column('descuento_global', sa.Numeric(scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(scale=2), nullable=False),
    sa.Column('total', sa.Numeric(scale=2), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metodo_pago', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('forma_pago', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notas_privadas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('folio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('proyecto', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('personas', sa.Integer(), nullable=False),
    sa.Column('origen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('destino', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_salida', sa.Date(), nullable=True),
    sa.Column('fecha_regreso', sa.Date(), nullable=True),
    sa.Column('costo_transporte', sa.Numeric(scale=2), nullable=False),
    sa.Column('costo_alojamiento', sa.Numeric(scale=2), nullable=False),
    sa.Column('costo_alimentos', sa.Numeric(scale=2), nullable=False),
    sa.Column('costo_otros', sa.Numeric(scale=2), nullable=False),
    sa.Column('notas_desglose', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viaticos_cliente_id'), 'viaticos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_viaticos_estado'), 'viaticos', ['estado'], unique=False)
    op.create_index(op.f('ix_viaticos_folio'), 'viaticos', ['folio'], unique=True)
    op.create_index(op.f('ix_viaticos_responsable_id'), 'viaticos', ['responsable_id'], unique=False)
    op.create_table('viatico_orden_enlace',
    sa.Column('viatico_id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordentrabajo.id'], ),
    sa.ForeignKeyConstraint(['viatico_id'], ['viaticos.id'], ),
    sa.PrimaryKeyConstraint('viatico_id', 'orden_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viatico_orden_enlace')
    op.drop_index(op.f('ix_viaticos_responsable_id'), table_name='viaticos')
    op.drop_index(op.f('ix_viaticos_folio'), table_name='viaticos')
    op.drop_index(op.f('ix_viaticos_estado'), table_name='viaticos')
    op.drop_index(op.f('ix_viaticos_cliente_id'), table_name='viaticos')
    op.drop_table('viaticos')
    # ### end Alembic commands ###
