"""rbac_and_standardization

Revision ID: 6dc8da608b1e
Revises: 
Create Date: 2026-03-19 02:01:31.085738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc8da608b1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('permisos_ver', sa.JSON(), nullable=True))
    op.add_column('usuario', sa.Column('permisos_crear', sa.JSON(), nullable=True))
    op.add_column('usuario', sa.Column('permisos_editar', sa.JSON(), nullable=True))
    op.add_column('usuario', sa.Column('permisos_eliminar', sa.JSON(), nullable=True))
    
    # Lista de módulos actuales para migración inicial de admins
    modulos_full = '["clientes", "servicios", "proveedores", "cotizaciones", "ordenes", "ordenes-compra", "usuarios"]'
    
    # Inicializar con todos los permisos para administradores actuales para evitar bloqueos
    op.execute(f"UPDATE usuario SET permisos_ver = '{modulos_full}', permisos_crear = '{modulos_full}', permisos_editar = '{modulos_full}', permisos_eliminar = '{modulos_full}' WHERE rol = 'admin'")
    
    # Inicializar con arreglos vacíos para los demás usuarios
    op.execute("UPDATE usuario SET permisos_ver = '[]', permisos_crear = '[]', permisos_editar = '[]', permisos_eliminar = '[]' WHERE rol != 'admin' OR rol IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
