"""crear_tabla_logs

Revision ID: 567193e68bcd
Revises: a1b2c3d4e5f6
Create Date: 2026-05-14 03:10:06.999926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '567193e68bcd'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs_actividad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detalles', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_actividad_accion'), 'logs_actividad', ['accion'], unique=False)
    op.create_index(op.f('ix_logs_actividad_fecha'), 'logs_actividad', ['fecha'], unique=False)
    op.create_index(op.f('ix_logs_actividad_modulo'), 'logs_actividad', ['modulo'], unique=False)
    op.create_index(op.f('ix_logs_actividad_usuario'), 'logs_actividad', ['usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_actividad_usuario'), table_name='logs_actividad')
    op.drop_index(op.f('ix_logs_actividad_modulo'), table_name='logs_actividad')
    op.drop_index(op.f('ix_logs_actividad_fecha'), table_name='logs_actividad')
    op.drop_index(op.f('ix_logs_actividad_accion'), table_name='logs_actividad')
    op.drop_table('logs_actividad')
    # ### end Alembic commands ###
