"""add_snapshot_fields_to_viaticos

Revision ID: e63da54c712d
Revises: a1347a9d9e40
Create Date: 2026-04-13 07:18:28.547183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e63da54c712d'
down_revision: Union[str, Sequence[str], None] = 'a1347a9d9e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cotizaciones', 'metodo_pago',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cotizaciones', 'forma_pago',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ordentrabajo', 'unidad_duracion',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'horas'::character varying"))
    op.add_column('viaticos', sa.Column('cliente_direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('viaticos', sa.Column('cliente_ciudad', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('viaticos', sa.Column('cliente_cp', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True))
    op.add_column('viaticos', sa.Column('cliente_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('viaticos', 'cotizacion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('viaticos', 'dias',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('viaticos', 'desayuno',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('viaticos', 'comida',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('viaticos', 'cena',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('viaticos', 'cena',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('viaticos', 'comida',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('viaticos', 'desayuno',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('viaticos', 'dias',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('viaticos', 'cotizacion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('viaticos', 'cliente_email')
    op.drop_column('viaticos', 'cliente_cp')
    op.drop_column('viaticos', 'cliente_ciudad')
    op.drop_column('viaticos', 'cliente_direccion')
    op.alter_column('ordentrabajo', 'unidad_duracion',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'horas'::character varying"))
    op.alter_column('cotizaciones', 'forma_pago',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cotizaciones', 'metodo_pago',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
