"""add_audit_to_details

Revision ID: 2013841ebed6
Revises: bf5b4b69df12
Create Date: 2026-04-27 03:22:46.657615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2013841ebed6'
down_revision: Union[str, Sequence[str], None] = 'bf5b4b69df12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concepto_orden_trabajo', sa.Column('fecha_modificacion', sa.DateTime(timezone=True), nullable=True))
    op.add_column('concepto_orden_trabajo', sa.Column('modificado_por', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('conceptocotizacion', sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text("date_trunc('second', now())"), nullable=False))
    op.add_column('conceptocotizacion', sa.Column('fecha_modificacion', sa.DateTime(timezone=True), nullable=True))
    op.add_column('conceptocotizacion', sa.Column('creado_por', sqlmodel.sql.sqltypes.AutoString(), server_default='SISTEMA', nullable=False))
    op.add_column('conceptocotizacion', sa.Column('modificado_por', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('cotizaciones', 'metodo_pago',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cotizaciones', 'forma_pago',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('detalle_orden_compra', sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text("date_trunc('second', now())"), nullable=False))
    op.add_column('detalle_orden_compra', sa.Column('fecha_modificacion', sa.DateTime(timezone=True), nullable=True))
    op.add_column('detalle_orden_compra', sa.Column('creado_por', sqlmodel.sql.sqltypes.AutoString(), server_default='SISTEMA', nullable=False))
    op.add_column('detalle_orden_compra', sa.Column('modificado_por', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detalle_orden_compra', 'modificado_por')
    op.drop_column('detalle_orden_compra', 'creado_por')
    op.drop_column('detalle_orden_compra', 'fecha_modificacion')
    op.drop_column('detalle_orden_compra', 'fecha_creacion')
    op.alter_column('cotizaciones', 'forma_pago',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cotizaciones', 'metodo_pago',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('conceptocotizacion', 'modificado_por')
    op.drop_column('conceptocotizacion', 'creado_por')
    op.drop_column('conceptocotizacion', 'fecha_modificacion')
    op.drop_column('conceptocotizacion', 'fecha_creacion')
    op.drop_column('concepto_orden_trabajo', 'modificado_por')
    op.drop_column('concepto_orden_trabajo', 'fecha_modificacion')
    # ### end Alembic commands ###
