"""add_missing_viatico_fields

Revision ID: bf5b4b69df12
Revises: e63da54c712d
Create Date: 2026-04-20 08:33:37.161611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bf5b4b69df12'
down_revision: Union[str, Sequence[str], None] = 'e63da54c712d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ordentrabajo_cotizacion_id', table_name='orden_trabajo')
    op.drop_index('ix_ordentrabajo_estado', table_name='orden_trabajo')
    op.drop_index('ix_ordentrabajo_numero_ot', table_name='orden_trabajo')
    op.drop_index('ix_ordentrabajo_tecnico_id', table_name='orden_trabajo')
    op.create_index(op.f('ix_orden_trabajo_cotizacion_id'), 'orden_trabajo', ['cotizacion_id'], unique=False)
    op.create_index(op.f('ix_orden_trabajo_estado'), 'orden_trabajo', ['estado'], unique=False)
    op.create_index(op.f('ix_orden_trabajo_numero_ot'), 'orden_trabajo', ['numero_ot'], unique=True)
    op.create_index(op.f('ix_orden_trabajo_tecnico_id'), 'orden_trabajo', ['tecnico_id'], unique=False)
    op.add_column('viaticos', sa.Column('cliente_telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viaticos', 'cliente_telefono')
    op.drop_index(op.f('ix_orden_trabajo_tecnico_id'), table_name='orden_trabajo')
    op.drop_index(op.f('ix_orden_trabajo_numero_ot'), table_name='orden_trabajo')
    op.drop_index(op.f('ix_orden_trabajo_estado'), table_name='orden_trabajo')
    op.drop_index(op.f('ix_orden_trabajo_cotizacion_id'), table_name='orden_trabajo')
    op.create_index('ix_ordentrabajo_tecnico_id', 'orden_trabajo', ['tecnico_id'], unique=False)
    op.create_index('ix_ordentrabajo_numero_ot', 'orden_trabajo', ['numero_ot'], unique=True)
    op.create_index('ix_ordentrabajo_estado', 'orden_trabajo', ['estado'], unique=False)
    op.create_index('ix_ordentrabajo_cotizacion_id', 'orden_trabajo', ['cotizacion_id'], unique=False)
    # ### end Alembic commands ###
