"""add_viatico_snapshots_and_validators

Revision ID: a1347a9d9e40
Revises: ef321a123f4a
Create Date: 2026-04-06 03:18:32.599051

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1347a9d9e40'
down_revision: Union[str, Sequence[str], None] = 'ef321a123f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viaticos', sa.Column('cliente_nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('viaticos', sa.Column('cliente_rfc', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('viaticos', 'cotizacion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('viaticos', 'cotizacion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('viaticos', 'cliente_rfc')
    op.drop_column('viaticos', 'cliente_nombre')
    # ### end Alembic commands ###
