"""Add financial fields to concepto_orden_trabajo

Revision ID: da5b731a1ea2
Revises: 6dc8da608b1e
Create Date: 2026-03-25 04:01:48.924716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da5b731a1ea2'
down_revision: Union[str, Sequence[str], None] = '6dc8da608b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concepto_orden_trabajo', sa.Column('descuento_porcentaje', sa.Numeric(scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concepto_orden_trabajo', 'descuento_porcentaje')
    # ### end Alembic commands ###
